services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV="production"
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    volumes:
      - /app/node_modules # Prevents overwriting node_modules inside container
    command: ['pnpm', 'run', 'start']
