version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_VERSION: "1.22.2" 
    ports:
      - "3000:3000"
    environment:
      - ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    command: ["/usr/local/bin/run-app"]
