services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_VERSION: "1.24.1" 
    ports:
      - "3000:3000"
    env_file:
      - .envrc
    environment:
      - ENV=production
    command: ["/usr/local/bin/run-app"]
